In [1]:
!nvidia-smi


/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [4]:
scalar = torch.tensor(7)

In [8]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))

random_tensor.device

device(type='cpu')

In [10]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B.T) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [13]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x.T)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[0.9332, 0.8805, 3.0149, 1.5545, 1.8186, 2.0634],
        [1.7186, 1.4009, 3.5818, 1.7408, 2.6017, 2.5123]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([2, 6])


In [17]:
# Create tensor with specific shape
x_original = torch.rand(size=(2, 1, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(x_original)
print(x_permuted)
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

tensor([[[0.4751, 0.1985, 0.1941]],

        [[0.0521, 0.3370, 0.6689]]])
tensor([[[0.4751],
         [0.0521]],

        [[0.1985],
         [0.3370]],

        [[0.1941],
         [0.6689]]])
Previous shape: torch.Size([2, 1, 3])
New shape: torch.Size([3, 2, 1])
